version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: authapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: monmotdepasse
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/authapi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=monmotdepasse
    ports:
      - "8080:8080"

volumes:
  postgres-data:
